week9/exercises/ironbnb/config/routes.rb
Rails.application.routes.draw do

  # get '/' => 'site#home'
  
  root 'site#home'

  get '/become_a_host' => 'site#becomeAHost'

  get '/wish_lists' => 'site#wishLists'

  get '/help' => 'site#help'

  get '/sign_up' => 'site#signUp'

  get '/log_in' => 'site#logIn'

end

week9/exercises/ironbnb/app/models/home.rb
class Home < ActiveRecord::Base
end

week9/exercises/ironbnb/app/controllers/site_controller.rb
class SiteController < ApplicationController

	def home 
	end

	def becomeAHost
	end

	def help
	end

	def signUp
	end

	def logIn
	end

end

week9/exercises/ironbnb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ironbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">

	<div class="row header">

  		<div class="col-sm-1"><center>
			<%= link_to " add logo ", '/' %>
		</center></div>

		<div class="col-sm-6">
			"Where are you going _____ ?"
		</center></div>

		<div class="col-sm-1">
			<%= link_to "Become a Host", become_a_host_path %>
		</center></div>

		<div class="col-sm-1">
			<%= link_to "Wish Lists", wish_lists_path %>	
		</center></div>

		<div class="col-sm-1">
				<%= link_to "Help", help_path %>
		</center></div>

		<div class="col-sm-1">
				<%= link_to "Sign Up",sign_up_path %>
		</center></div>

		<div class="col-sm-1">
				<%= link_to "Log in", log_in_path %>
		</center></div>

	</div>
</div>

<%= yield %>

</body>
</html>