week10/exercises/auction_site/config/routes.rb
Rails.application.routes.draw do

  get 'bid/create'

  get '/' => 'users#home'

    resources :users, only: [:index, :show, :create, :destroy, :new] do 

      resources :products, only: [:index, :show, :create, :destroy, :new] 
      	
    end

    resources :bids, only: [:create] do 

    end

end

week10/exercises/auction_site/app/models/bid.rb
class Bid < ActiveRecord::Base
	belongs_to :product

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
end

week10/exercises/auction_site/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :bids

	def self.last_created_products(n)
		limit(n).order(created_at: :desc)
	end
end

week10/exercises/auction_site/app/models/user.rb
class User < ActiveRecord::Base
	has_many :products

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true

end

week10/exercises/auction_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week10/exercises/auction_site/app/controllers/bid_controller.rb
class BidController < ApplicationController
  def create
  end
end

week10/exercises/auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def new
		@user = User.find_by(params[:user_id])
		@product = @user.products.new
	end

	def index 
		@user = User.find_by(params[:user_id])
		@products = @user.products.all
	end

	def create
		@user = User.find_by(params[:user_id])
		@product = @user.products.new(
			title: params[:product][:title], 
			description: params[:product][:description],
			deadline: params[:product][:deadline]
			)
		@product.save

		redirect_to new_user_product_path(@user)
	end

	def show
		@user = User.find(params[:user_id])
		@product = @user.products.find(params[:id])
		@bid = @user.products.new

	end

end

week10/exercises/auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def home 
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(
			name: params[:user][:name], 
			email: params[:user][:email]
			)
		@user.save

		redirect_to '/users'
	end

	def index
		@users= User.all
	end

	def show 
		@user = User.find_by(params[:user_id])
	end

end

week10/exercises/auction_site/app/helpers/bid_helper.rb
module BidHelper
end

week10/exercises/auction_site/app/helpers/products_helper.rb
module ProductsHelper
end

week10/exercises/auction_site/app/views/products/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Auction Site</title>
</head>
<body>
	<h1>This is a list of the most recent products</h1>

	<ul>
		<% @products.each do |product| %>
			<li> <strong> <%=link_to product.title,user_product_path(@user,product)%></strong>
				<% if product.description.present? %>
					- <%= product.description %> 
				<% end %>
			</li>
		<br>
	<% end %>
	</ul>
</body>
</html>

week10/exercises/auction_site/app/views/products/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Auction site</title>
</head>
<body>
	<%= form_for [@user, @product] do |f| %>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<br>
		<%= f.label :description %>
		<%= f.text_field :description %>
		<br>
		<%= f.label :deadline %>
		<%= f.date_field :deadline %>
		<br>
		<%= f.submit 'Save' %>

	<% end %>


</body>
</html>

week10/exercises/auction_site/app/views/products/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Auction Site</title>
</head>
<body>
	<h1> <%= @product.title %> </h1>
	<h3> <%= @product.description%> </h3>
	<h4> <%= @product.deadline %> </h4>

	<%= form_for [@product, @bid] do |f| %>
		<%= f.label :amount %>
		<%= f.text_field :amount %>
		<br>
		<%= f.submit 'Save' %>

	<% end %>

</body>
</html>