week16/exercises/GIF_blog/gif_blog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'posts#home'

  get '/posts/' => 'posts#index'

  get '/posts/new' => 'posts#new'

  get 'posts/:id' => 'posts#show'

  post '/posts' => 'posts#create' 

  post 'posts/:id/upvote' => 'posts#upvote' 

  post 'posts/:id/downvote' => 'posts#downvote' 

end

week16/exercises/GIF_blog/gif_blog/app/models/post.rb
class Post < ApplicationRecord

	def upvote
		votes = self.nov
		update(nov: votes + 1)
	end

	def downvote
		votes = self.nov
		update(nov: votes - 1)
	end
end

week16/exercises/GIF_blog/gif_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

week16/exercises/GIF_blog/gif_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def home
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(
			title: params[:post][:title],
			gif_url: params[:post][:gif_url],
			)
		@post.save

		redirect_to '/posts'
	end

	def index
		@posts = Post.all
	end

	def show 
		@post = Post.find(params[:id])
	end

	def upvote
  		@post = Post.find(params[:id])
  		@post.upvote
  		
  		redirect_to post_path(@post.id)
	end

	def downvote
  		@post = Post.find(params[:id])
  		@post.downvote
  		
  		redirect_to post_path(@post.id)
	end

end

week16/exercises/GIF_blog/gif_blog/app/helpers/posts_helper.rb
module PostsHelper
end

week16/exercises/GIF_blog/gif_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GifBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

week16/exercises/GIF_blog/gif_blog/app/views/posts/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>GIFblog</title>
</head>
<body>
	<h1>Top posts</h1>


</body>
</html>

week16/exercises/GIF_blog/gif_blog/app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>GIFblog</title>
</head>
<body>
	<h1>This is the list of posts</h1>

	<ul>
		<% @posts.each do |post| %>
			<li> 
				<strong><%= post.id %> <%= post.title %></strong>
				<br>
				<p><%= "this gif has this many votes: #{post.nov}" %></p>
				<%= link_to(post.title, posts_path(@post)) %>
			</li>
		<br>
	<% end %>
	</ul>

	<p><%= link_to("Create New", posts_new_path) %></p>
</body>
</html>

week16/exercises/GIF_blog/gif_blog/app/views/posts/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>GIFblog</title>
</head>
<body>

	<p>Enter a gif url:</p>

	<%= form_for [@post] do |f| %>
		<%= f.label :gif_url %>
		<%= f.text_field :gif_url %>
		<br>
		<%= f.label :title %>
		<%= f.text_field :title %>
		<br>
		<%= f.submit 'Save' %>

	<% end %>

	<p><%= link_to("Back to All", posts_path) %></p>

</body>
</html>

week16/exercises/GIF_blog/gif_blog/app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>GIFblog</title>
</head>
<body>
	
	
	<form action="/posts/<%= @post.id%>/upvote" method="POST">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<button type="submit">Upvote</button>

	</form>

	<form action="/posts/<%= @post.id%>/downvote" method="POST">
		<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
		<button type="submit" name="button">Downvote</button>
	</form>

	<p><%= "Vote Count: #{@post.nov}" %></p>

	<img src="<%=@post.gif_url%>">
	
	<p><%= link_to("Create New", posts_new_path) %></p>
	<p><%= link_to("Back to All", posts_path) %></p>

</body>
</html>