week9/exercises/timetracking/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'site#home'
  get '/contact' => 'site#contact'

  	resources :projects, only: [:index, :show, :new, :create] do 
  		resources :time_entries, except: [:show]
  	end
end

week9/exercises/timetracking/app/models/project.rb
class Project < ActiveRecord::Base
has_many :time_entries
validates :name, uniqueness: true, presence: true, length: { maximum: 30 }, format: { with: /[a-zA-Z0-9]/ }

	def self.clean_old
		where("created_at < ?", 1.week.ago).destroy_all
	end

	def self.last_created_projects(n)
		limit(n).order(created_at: :desc)
	end

	def total_hours_in_month(month, year)
		date = Time.new(year, month)
		entries_in_month = time_entries.where(
			date: date..date.end_of_month
		)
		hours = entries_in_month.sum { |e| e.hours }
		minutes = entires_in_month.sum { |e| e.minutes }
		(minutes /60) + hours
	end
end 

week9/exercises/timetracking/app/models/time_entry.rb
class TimeEntry < ActiveRecord::Base
	belongs_to :project
	validates :project, presence: true
	validates :hours, :minutes, presence: true, numericality: true
end

week9/exercises/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.last_created_projects(10)
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(
			name: params[:project][:name], 
			description: params[:project][:description]
			)
		@project.save

		redirect_to '/projects'
	end

	def show
		@project = Project.find_by(id:params[:id])
		unless @project
			render 'no_projects_found'
		end
	end

	# def show
	# 	begin
	# 		@project = Project.find(params[:id])
	# 	rescue ActiveRecord::RecordNotFound
	# 		render 'no_projects_found'
	# 		# redirect_to '/projects'
	# 	end
	# end
end

week9/exercises/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end

	def contact 
	end

end

week9/exercises/timetracking/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController

	def update
		# input: project_id, time_entry_id
		# find resources needed
		@project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])
		if @time_entry.update(time_entry_params)
			redirect_to project_time_entries_path(@project)
		else
			render 'edit'
		end
	end

	def create 
		@project = Project.find(params[:project_id])
		time_entry_params = params.require(:time_entry).permit(
				:hours, :minutes, :date
			)
		@time_entry = @project.time_entries.new(time_entry_params)
		if @time_entry.save
			redirect_to project_time_entries_path(@project)
		else
			render 'new'
		end
	end

	def index
		@project = Project.find(params[:project_id])
		@time_entries = @project.time_entries
	end

	def new
		@project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.new
	end

	def edit 
		@project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])
	end

	def destroy
		flash[:hello] = "World"
		# find time entry
		@project = Project.find(params[:project_id])
		@time_entry = @project.time_entries.find(params[:id])

		@time_entry.destroy
		redirect_to project_time_entries_path(@project)
	end

	private

	def time_entry_params
		params.require(:time_entry).permit(
				:hours, :minutes, :date, :comment
			)
	end

end

week9/exercises/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

week9/exercises/timetracking/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

week9/exercises/timetracking/app/views/time_entries/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Timetracking</title>
</head>
<body>
	<% if time_entry.errors.any? %>
		<ul>
			<% time_entry.errors.full_messages.each do |error_msg| %> 
			<li><%= error_msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= form_for [@project, @time_entry] do |f| %>
		<%= f.label :hours %>
		<%= f.text_field :hours, size: 4 %>
		<br>
		<%= f.label :minutes %>
		<%= f.text_field :minutes, size: 4 %>
		<br>
		<%= f.label :date %>
		<%= f.date_field :date %>
		<br>
		<%= f.label :comments %>
		<%= f.text_area :comments %>
		<br>

		<%= f.submit 'Save' %>
		<%= link_to 'Cancel', project_time_entries_path(@project) %>
	<% end %>
</body>
</html>

week9/exercises/timetracking/app/views/time_entries/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Timetracking</title>
</head>
<body>
	<%= render partial: "form", locals: { project: @project, time_entry: @time_entry } %>
</body>
</html>

week9/exercises/timetracking/app/views/time_entries/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Index</title>
</head>
<body>
	<h1><%= @project.name %></h1>

	<ul>
		<% @time_entries.each do |time_entry| %>
			<li>
				Hours: 
				<%= time_entry.hours %>, 
				Minutes: 
				<%= time_entry.minutes %>
				Date: 
				<%= time_entry.date %>
				<%= link_to("Edit Time Entry", edit_project_time_entry_path(@project, time_entry)) %>
				<%= link_to('Delete', project_time_entry_path(@project, time_entry), method: :delete, data: {confirm: 'Are you sure?'}) %>
			</li>
		<% end %>
	</ul>
	<ul>
		<%= link_to("Projects", projects_path) %>
		<%= link_to("Create new entry", new_project_time_entry_path(@project)) %>

	</ul>
</body>
</html>

week9/exercises/timetracking/app/views/time_entries/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>New</title>
</head>
<body>

<%= render partial: "form", locals: { project: @project, time_entry: @time_entry } %>

</body>
</html>